package:
  name: "nfl_data_py"
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/cooperdff/nfl_data_py

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pandas
	- numpy
	- datetime

about:
  home: https://github.com/cooperdff/nfl_data_py
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Access NFL data"

extra:
  recipe-maintainers:
    - cooperdff